/**
 * StMessageIframe — message-level iframe React component for card rendering.
 *
 * Ported from JS-Slash-Runner (JSR):
 *   SillyTavern-release/public/scripts/extensions/third-party/JS-Slash-Runner/src/panel/render/Iframe.vue
 *
 * Key behaviors (matching JSR):
 * - Blob URL lifecycle: revoke old → create new on srcdoc change; revoke on unmount
 * - iframe id/name = iframeName (TH-message--X--Y) for predefine.js window.name / frameElement.id
 * - Viewport height sync via postMessage (the ONLY retained postMessage channel)
 * - Render lifecycle events: MESSAGE_IFRAME_RENDER_STARTED on mount, MESSAGE_IFRAME_RENDER_ENDED on load
 * - No sandbox attribute (same-origin trust model, consistent with ST)
 * - Height is set by iframe-internal adjust_iframe_height.js via frameElement.style.height
 *
 * This component is pure presentational — no variable handling, no API calls,
 * no postMessage th_api dispatch. Those concerns live in the parent runtime layer.
 */

import React, { useEffect, useRef, useState } from 'react';
import { eventSource, iframe_events } from './events';

interface StMessageIframeProps {
  /** Complete srcdoc HTML (generated by createMessageSrcContent) */
  srcdoc: string;
  /** iframe name/id identifier, e.g. TH-message--0--0 */
  iframeName: string;
  /** CSS class name */
  className?: string;
  /** Whether to hide from assistive technologies */
  ariaHidden?: boolean;
  /** Tab index for keyboard navigation */
  tabIndex?: number;
}

export function StMessageIframe({
  srcdoc,
  iframeName,
  className,
  ariaHidden,
  tabIndex,
}: StMessageIframeProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const blobUrlRef = useRef<string | null>(null);
  const [isRendered, setIsRendered] = useState(false);

  // ---------------------------------------------------------------
  // Blob URL lifecycle (matches Iframe.vue computed src_prop logic)
  // Only recreates when srcdoc actually changes.
  // ---------------------------------------------------------------
  useEffect(() => {
    // Revoke previous blob URL
    if (blobUrlRef.current) {
      URL.revokeObjectURL(blobUrlRef.current);
    }

    // Create new blob URL from srcdoc
    const blob = new Blob([srcdoc], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    blobUrlRef.current = url;
    setIsRendered(false);

    // Set src directly on the already-mounted iframe element
    if (iframeRef.current) {
      iframeRef.current.src = url;
    }

    // Cleanup on unmount
    return () => {
      if (blobUrlRef.current) {
        URL.revokeObjectURL(blobUrlRef.current);
        blobUrlRef.current = null;
      }
    };
  }, [srcdoc]);

  // ---------------------------------------------------------------
  // Viewport height sync (the ONLY retained postMessage)
  // Matches Iframe.vue lines 34-36: useEventListener(window, 'resize', ...)
  // ---------------------------------------------------------------
  useEffect(() => {
    const onResize = () => {
      iframeRef.current?.contentWindow?.postMessage(
        { type: 'TH_UPDATE_VIEWPORT_HEIGHT' },
        '*',
      );
    };
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);

  // ---------------------------------------------------------------
  // Render lifecycle events (matches Iframe.vue onMounted / onLoad)
  // ---------------------------------------------------------------
  useEffect(() => {
    eventSource.emit(iframe_events.MESSAGE_IFRAME_RENDER_STARTED, iframeName);
  }, [iframeName]);

  return (
    <iframe
      ref={iframeRef}
      id={iframeName}
      name={iframeName}
      className={`${className ?? ''}${isRendered ? ' sandbox-rendered' : ''}`}
      aria-hidden={ariaHidden}
      tabIndex={tabIndex}
      loading="lazy"
      frameBorder="0"
      style={{ width: '100%', height: 'auto', border: 0, display: 'block' }}
      onLoad={() => {
        setIsRendered(true);
        eventSource.emit(iframe_events.MESSAGE_IFRAME_RENDER_ENDED, iframeName);
      }}
      title="消息级角色卡界面"
    />
  );
}
